version: '3.7'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  # server:
  #   build:
  #     context: ./
  #     target: development-build-stage
  #     dockerfile: Dockerfile
  #   container_name: server
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    # network_mode: "host"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: practum_db
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:

volumes:
  postgres:
