tags:
- name: users
  description: users API
- name: areas
  description: areas API
- name: groups
  description: groups API

paths:
  /areas:
    get:
      tags:
      - areas
      summary: Find All Areas
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
      - areas
      summary: Add Area
      parameters:
      - name: body
        in: body
        description: area Data
        required: true
        schema:
          $ref: '#/definitions/areas'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] areas/id
  /areas/{id}:
    get:
      tags:
      - areas
      summary: Find Area By Id
      parameters:
      - name: id
        in: path
        description: Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] users/id
    put:
      tags:
      - areas
      summary: Update Area By Id
      parameters:
      - name: id
        in: path
        description: Id
        required: true
        type: integer
      - name: body
        in: body
        description: area Data
        required: true
        schema:
          $ref: '#/definitions/areas'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] users/id
    delete:
      tags:
      - areas
      summary: Delete Area By Id
      parameters:
      - name: id
        in: path
        description: area Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /groups:
    get:
      tags:
      - groups
      summary: Find All Groups
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
      - groups
      summary: Add Group
      parameters:
      - name: body
        in: body
        description: group Data
        required: true
        schema:
          $ref: '#/definitions/groups'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] areas/id
  /groups/{id}:
    get:
      tags:
      - groups
      summary: Find Group By Id
      parameters:
      - name: id
        in: path
        description: Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] users/id
    put:
      tags:
      - groups
      summary: Update Group By Id
      parameters:
      - name: id
        in: path
        description: Id
        required: true
        type: integer
      - name: body
        in: body
        description: group Data
        required: true
        schema:
          $ref: '#/definitions/groups'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] users/id
    delete:
      tags:
      - groups
      summary: Delete Groups By Id
      parameters:
      - name: id
        in: path
        description: group Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'



# [GET] users
  /users:
    get:
      tags:
      - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] users
    post:
      tags:
      - users
      summary: Add User
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] users/id
  /users/{id}:
    get:
      tags:
      - users
      summary: Find User By Id
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] users/id
    put:
      tags:
      - users
      summary: Update User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] users/id
    delete:
      tags:
      - users
      summary: Delete User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  

# definitions
definitions:
  areas:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: "Name of the area"
  groups:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: "Name of the group"
  users:
    type: object
    required:
        - email
        - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

schemes:
 - https
 - http
