tags:
  - name: users
    description: users API
  - name: areas
    description: areas API
  - name: groups
    description: groups API
  - name: authentication
    description: Auth API

paths:
  /api/auth:
    get:
      tags:
        - authentication
      summary: 'Check for auth token'
      response:
        200:
          description: 'OK'
  /api/auth/signup:
    post:
      tags:
        - authentication
      summary: Create a new account
      parameters:
        - name: body
          in: body
          description: 'Sign up body reqs'
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
  /api/auth/login:
    post:
      tags:
        - authentication
      summary: Login to existing account
      parameters:
        - name: body
          in: body
          description: 'Login body reqs'
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
  /api/auth/logout:
    post:
      tags:
        - authentication
      summary: Create a new account
      responses:
        200:
          description: 'OK'

  /api/entries:
    get:
      tags:
        - entries
      summary: Find All Entries
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
        - entries
      summary: Add Entries
      parameters:
        - name: body
          in: body
          description: entry Data
          required: true
          schema:
            $ref: '#/definitions/entries'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /api/entries/{id}:
    put:
      tags:
        - entries
      summary: Update Entry By Id
      parameters:
        - name: id
          in: path
          description: entry Id
          required: true
          type: integer
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/entries'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    delete:
      tags:
        - entries
      summary: Delete entry By Id
      parameters:
        - name: id
          in: path
          description: entry Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /api/tools:
    get:
      tags:
        - tools
      summary: Find All Tools
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
        - tools
      summary: Add Tools
      parameters:
        - name: body
          in: body
          description: tool Data
          required: true
          schema:
            $ref: '#/definitions/tools'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /api/tools/{id}:
    put:
      tags:
        - tools
      summary: Update Tool By Id
      parameters:
        - name: id
          in: path
          description: tool Id
          required: true
          type: integer
        - name: body
          in: body
          description: tool Data
          required: true
          schema:
            $ref: '#/definitions/tools'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    delete:
      tags:
        - tools
      summary: Delete tool By Id
      parameters:
        - name: id
          in: path
          description: tool Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # end

  /api/outputs:
    get:
      tags:
        - outputs
      summary: Find All Outputs
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
        - outputs
      summary: Add Outputs
      parameters:
        - name: body
          in: body
          description: Output Data
          required: true
          schema:
            $ref: '#/definitions/outputs'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /api/outputs/{id}:
    put:
      tags:
        - outputs
      summary: Update Output By Id
      parameters:
        - name: id
          in: path
          description: output Id
          required: true
          type: integer
        - name: body
          in: body
          description: output Data
          required: true
          schema:
            $ref: '#/definitions/outputs'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    delete:
      tags:
        - outputs
      summary: Delete output By Id
      parameters:
        - name: id
          in: path
          description: output Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] areas/id
  /api/areas:
    get:
      tags:
        - areas
      summary: Find All Areas
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
        - areas
      summary: Add Area
      parameters:
        - name: body
          in: body
          description: area Data
          required: true
          schema:
            $ref: '#/definitions/areas'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] areas/id
  /api/areas/{id}:
    get:
      tags:
        - areas
      summary: Find Area By Id
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] users/id
    put:
      tags:
        - areas
      summary: Update Area By Id
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          type: integer
        - name: body
          in: body
          description: area Data
          required: true
          schema:
            $ref: '#/definitions/areas'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] users/id
    delete:
      tags:
        - areas
      summary: Delete Area By Id
      parameters:
        - name: id
          in: path
          description: area Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /api/process:
    get:
      tags:
        - processes
      summary: Find All processes
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
        - processes
      summary: Add process
      parameters:
        - name: body
          in: body
          description: process Data
          required: true
          schema:
            $ref: '#/definitions/processes'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] process/id
  /api/process/filter/{areaId}&{groupId}:
    get:
      tags:
        - processes
      summary: Find processes By area & group Id
      parameters:
        - name: areaId
          in: path
          description: area id
          required: true
          type: integer
        - name: groupId
          in: path
          description: group id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] process/id
  /api/process/{id}:
    get:
      tags:
        - processes
      summary: Find process By Id
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] process/id
    put:
      tags:
        - processes
      summary: Update process By Id
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          type: integer
        - name: body
          in: body
          description: process Data
          required: true
          schema:
            $ref: '#/definitions/processes'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] process/id
    delete:
      tags:
        - processes
      summary: Delete process By Id
      parameters:
        - name: id
          in: path
          description: group Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /api/groups:
    get:
      tags:
        - groups
      summary: Find All Groups
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
        - groups
      summary: Add Group
      parameters:
        - name: body
          in: body
          description: group Data
          required: true
          schema:
            $ref: '#/definitions/groups'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] areas/id
  /api/groups/{id}:
    get:
      tags:
        - groups
      summary: Find Group By Id
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] users/id
    put:
      tags:
        - groups
      summary: Update Group By Id
      parameters:
        - name: id
          in: path
          description: Id
          required: true
          type: integer
        - name: body
          in: body
          description: group Data
          required: true
          schema:
            $ref: '#/definitions/groups'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] users/id
    delete:
      tags:
        - groups
      summary: Delete Groups By Id
      parameters:
        - name: id
          in: path
          description: group Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] users
  /api/users:
    get:
      tags:
        - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    # [POST] users
    post:
      tags:
        - users
      summary: Add User
      parameters:
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] users/id
  /api/users/{id}:
    get:
      tags:
        - users
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] users/id
    put:
      tags:
        - users
      summary: Update User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
          type: integer
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] users/id
    delete:
      tags:
        - users
      summary: Delete User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  entries:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: 'Entry name'
      isExit:
        type: boolean
        description: 'mark if item is exit'
      description:
        type: string
        description: 'Entry description'
  tools:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: 'Tool name'
      description:
        type: string
        description: 'Tool description'
  outputs:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: 'Output name'
      description:
        type: string
        description: 'Output description'
  areas:
    type: object
    required:
      - name
    properties:
      order:
        type: integer
        description: 'Optional value, choose the order in which its displayed asc'
      name:
        type: string
        description: 'Name of the area'
  groups:
    type: object
    required:
      - name
    properties:
      order:
        type: integer
        description: 'Optional value, choose the order in which its displayed asc'
      name:
        type: string
        description: 'Name of the group'
  processes:
    type: object
    required:
      - name
      - areaId
      - groupId
    properties:
      name:
        type: string
        description: 'Name of the process'
      areaId:
        type: string
        description: 'area id related to process'
      groupId:
        type: string
        description: 'group id related to process'
      newEntries:
        type: array
        items:
          $ref: '#/definitions/entries'
        description: '[Entry] array with entry objects'
      existingEntries:
        type: array
        items:
          type: integer
        description: '[Int] array with existing category ids'
      newOutputs:
        type: array
        items:
          $ref: '#/definitions/outputs'
        description: '[Output] array with output objects'
      existingOutputs:
        type: array
        items:
          type: integer
        description: '[Int] array with existing output ids'
      newTools:
        type: array
        items:
          $ref: '#/definitions/tools'
        description: '[Tool] array with tool objects'
      existingTools:
        type: array
        items:
          type: integer
        description: '[Int] array with existing tool ids'
  users:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

schemes:
  - https
  - http
